### ISSUE TITLE
python manage.py migrate Not working

### ISSUE THREAD

**Issue by Antu7** [algolia/algoliasearch-django-example#2]
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/an2/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/an2/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/an2/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/an2/.local/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/an2/.local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/an2/.local/lib/python3.6/site-packages/algoliasearch_django/__init__.py", line 9, in <module>
    from . import registration
  File "/home/an2/.local/lib/python3.6/site-packages/algoliasearch_django/registration.py", line 193, in <module>
    algolia_engine = AlgoliaEngine()
  File "/home/an2/.local/lib/python3.6/site-packages/algoliasearch_django/registration.py", line 41, in __init__
    self.client = algoliasearch.Client(app_id, api_key)
  File "/home/an2/.local/lib/python3.6/site-packages/algoliasearch/client.py", line 110, in __init__
    self.api_key = api_key
  File "/home/an2/.local/lib/python3.6/site-packages/algoliasearch/client.py", line 143, in api_key
    if len(value) > MAX_API_KEY_LENGTH:
TypeError: object of type 'NoneType' has no len()

**Comment by danielw-mt** [comment]
Hello @Antu7 , did you fix this issue already? I get the exact same error

**Comment by Antu7** [comment]
After wasting few days try I give up. If you success please leave a comment. @D-Venture

**Comment by malik-Wortell** [comment]
Same here. Can't seem to find a working example of Algolia in Django. Keep getting random errors. This one being the latest one.

`.../lib/python3.6/site-packages/algoliasearch/client.py", line 143, in api_key
if len(value) > MAX_API_KEY_LENGTH:`

**Comment by malik-Wortell** [comment]
_value_ doesn't seem to be defined in that file, which is why it's of type "NoneType" and has no length.
Not sure if we're supposed to edit the algoliasearch package. Does this work for anyone else?

**Comment by tkrugg** [comment]
Hey Anthu7, you're just missing the env variables required. Please make sure you have created an Algolia app and did the following, like [explained in the README.md](https://github.com/algolia/algoliasearch-django-example#configure-the-credentials):

```shell
$ export ALGOLIA_APPLICATION_ID=XXXXX
$ export ALGOLIA_API_KEY=XXXXX
$ export ALGOLIA_SEARCH_API_KEY=XXXXX
```

I'll close this for now but please reopen if you're still experiencing the same error.
